export const categories = {
    "Fruits": [
        "lime",
        "lime juice",
        "lemon",
        "lemon juice",
        "pomegranate",
        "banana",
        "kiwi",
        "strawberries",
        "raspberries",
        "blueberries",
        "pineapple",
        "papaya",
        "avocado",
        "cherry tomatoes",
        "vine tomatoes",
        "tomatoes",
        "roma tomatoes"
    ],
    "Vegetables": [
        "avocado",
        "okra",
        "oyster mushrooms",
        "shiitake mushrooms",
        "portobello mushrooms",
        "chestnut mushrooms",
        "lemongrass",
        "garlic",
        "garlic cloves",
        "ginger",
        "red chillies",
        "spring onions",
        "brussel sprouts",
        "banana shallots",
        "shallots",
        "chickpeas",
        "aubergines",
        "baby aubergines",
        "whole aubergines",
        "vine tomatoes",
        "cherry tomatoes",
        "tomatoes",
        "red pepper",
        "red peppers",
        "yellow peppers",
        "red onion",
        "onion",
        "broccoli",
        "squash",
        "sweet potatoes",
        "courgettes",
        "sweetcorn",
        "artichokes",
        "spring greens",
        "potatoes",
        "basil",
        "coriander",
        "parsley",
        "flat-leaf parsley",
        "thyme",
        "spinach",
        "kale",
        "celery",
        "carrot",
        "fennel",
        "cucumber",
        "jalapeño",
        "scallions",
        "baby bok choy",
        "radishes",
        "parsnips"
    ],
    "Meat & Fish": [
        "tofu",
        "tempeh"
    ],
    "Dairy & Eggs": [
        "coconut yogurt",
        "eggs",
        "parmesan",
        "feta cheese",
        "stilton",
        "sour cream",
        "yogurt",
        "single cream",
        "almond milk",
        "coconut milk",
        "soy milk"
    ],
    "Grains & Pasta": [
        "jasmine rice",
        "polenta",
        "bulgur wheat",
        "brown lentils",
        "farro",
        "quinoa",
        "brown rice",
        "whole-grain spaghetti",
        "gluten-free pasta"
    ],
    "Canned & Jarred Goods": [
        "coconut milk",
        "chopped tomatoes",
        "tinned tomatoes",
        "black beans",
        "cannellini beans",
        "red kidney beans",
        "pitted green olives",
        "vegetable stock",
        "kalamata olives"
    ],
    "Spices & Seasonings": [
        "sea salt",
        "salt",
        "ground cumin",
        "ground coriander",
        "chilli powder",
        "chilli flakes",
        "chaat masala",
        "mango powder",
        "harissa",
        "smoked paprika",
        "chipotle chilli flakes",
        "ground turmeric",
        "bay leaf",
        "rosemary",
        "rosemary sprigs",
        "za'atar",
        "black pepper",
        "kaffir lime leaves",
        "tom yum paste",
        "tamarind paste",
        "soy sauce",
        "white miso paste",
        "capers",
        "red wine vinegar",
        "sriracha",
        "hot chilli sauce",
        "tamari",
        "rice wine vinegar",
        "balsamic vinegar",
        "apple cider vinegar",
        "dried oregano",
        "dried basil",
        "dried fennel",
        "dried sage",
        "italian seasoning",
        "ground cinnamon",
        "ground nutmeg",
        "ground ginger",
        "vanilla extract",
        "nutritional yeast",
        "baking powder",
        "baking soda",
        "cocoa powder",
        "dijon mustard",
        "kimchi"
    ],
    "Baking & Cooking": [
        "vegetable oil",
        "olive oil",
        "sesame oil",
        "brown sugar",
        "breadcrumbs",
        "extra virgin olive oil",
        "sunflower oil",
        "coconut oil",
        "maple syrup",
        "gluten-free flour",
        "cornmeal",
        "rolled oats",
        "old-fashioned oats",
        "quick-cooking oats"
    ],
    "Frozen Foods": [],
    "Nuts & Seeds": [
        "cashews",
        "salted peanuts",
        "flaked almonds",
        "whole almonds",
        "almonds",
        "toasted almonds",
        "walnuts",
        "sesame seeds",
        "pumpkin seeds",
        "hemp seeds",
        "chia seeds",
        "ground flaxseed",
        "sunflower seeds",
        "almond butter",
        "peanut butter",
        "tahini",
    ],
    "Fresh Herbs": [
        "chives",
        "rosemary",
        "basil",
        "coriander",
        "parsley",
        "thyme",
        "sage",
        "dill",
        "mint",
        "cilantro"
    ],
    "Miscellaneous": [
        "tortillas",
        "nachos",
        "focaccia",
        "roasted italian medley",
        "garlic-infused olive oil"
    ]
};

type IngredientCategories = Record<string, string>;
export const ingredientCategories: IngredientCategories = {};

Object.entries(categories).forEach( ([category, ingredients]) => {
    for (const ingredient of ingredients) {
        ingredientCategories[ingredient] = category;
    }
});

export const getCatagoryForIngredient = (ingredientName: string) => {
    return ingredientCategories[ingredientName.toLowerCase()] || "Miscellaneous";
}

// test('getCatagoryForIngredient', () => {
//     assert.strictEqual(getCatagoryForIngredient('banana'), 'Fruits');
//     assert.strictEqual(getCatagoryForIngredient('chicken'), 'Meat & Fish');
//     assert.strictEqual(getCatagoryForIngredient('olive oil'), 'Baking & Cooking Essentials');
//     assert.strictEqual(getCatagoryForIngredient('chocolate'), 'Miscellaneous');
// });